## Numpy入門

### Numpyの特徴

numpy配列を使って、配列計算を行えます。  
NativeなPythonの機能と比較してNumpyを使うことにより次のメリットがあります。

* 処理速度が早くなる
* 配列の扱い方が柔軟
* コードがシンプルになる

より詳しい解説は例えば下記のリンク参照して下さい。  
[numpyの何がすごいのか？](https://to-kei.net/python/data-analysis/what-is-numpy/)


### 一次元配列

#### 宣言

In [1]:
# ライブラリのロード
import numpy as np

# 一次元配列の作成
# リスト配列を引数に、array関数でnumpy一次元配列を作ります。

list1 = list(range(2,12,2))
arr1 = np.array(list1)

In [2]:
# print文による表示結果の比較
# 画面上はカンマのあるなしで区別します。

print('list配列: ', list1)
print('numpy配列: ', arr1)
arr1

list配列:  [2, 4, 6, 8, 10]
numpy配列:  [ 2  4  6  8 10]


array([ 2,  4,  6,  8, 10])

In [3]:
# データ型(dtype)つき変数作成

# 個々の要素をデータ型付きで定義することも可能です。
# 型には、以下のようなものがあります。
#
# 符号付き整数: int8, int16, int32, int64
# 符号なし整数: unit8, uint16, uint32, uint64
# 浮動小数点: float16, float32, float64, float128

arr2 = np.array([2, 4, 6, 8,10], dtype=np.int32)
print(arr2)

arr2

[ 2  4  6  8 10]


array([ 2,  4,  6,  8, 10], dtype=int32)

In [4]:
# 型は' numpy.ndarray' となります

print(type(arr1))

<class 'numpy.ndarray'>


In [5]:
# 配列の要素数は'shape'という属性で取得可能です
# 結果はtuppleで返されます

print(arr1.shape)

(5,)


#### 参照

In [6]:
# 要素の参照例

# 先頭
print(arr1[0])

# 一番後ろの要素は-1で参照できます
print(arr1[-1])

2
10


In [7]:
# 範囲付き参照
# このパターンはlist変数と同じです。

# 0以上2未満
print(arr1[:2])

# 2以上
print(arr1[2:])

[2 4]
[ 6  8 10]


In [8]:
# こういうアクセス方法も可能です
# (これはlistではできない)

print(arr1[[0,2,4]])
print(arr1[[3,1]])

[ 2  6 10]
[8 4]


#### 計算

In [9]:
# 計算の例
# numpy配列を対象にすると計算を一気に行うことができます

arr1 = np.array(list(range(2,12,2)))
arr3 = np.array(list(range(5)))
print(arr1)
print(arr3)

[ 2  4  6  8 10]
[0 1 2 3 4]


In [10]:
# 足し算
# list変数だとループを回す必要があります

arr4 = arr1 + arr3
print(arr4)

[ 2  5  8 11 14]


In [11]:
# ブロードキャスト機能
# サイズの異なる変数同士の演算では、サイズを自動的に合わせて計算します

arr5 = arr1 + 3
print(arr5)

[ 5  7  9 11 13]


In [12]:
# 関数呼び出し
# numpy関数と組み合わせると、関数呼び出しも全要素分まとめて行えます

# 対数関数の呼出し
arr6 = np.log(arr1)
print(arr6)

[0.69314718 1.38629436 1.79175947 2.07944154 2.30258509]


In [13]:
# ブロードキャスト機能とindex機能を組み合わせてこんなことも可能です
# arr2 から偶数の要素だけを抜き出す

arr3 = np.array(list(range(5)))
w = (arr3 % 2) == 0
print(w)

[ True False  True False  True]


In [14]:
arr7 = arr3[w]
print(arr7)

[0 2 4]


In [15]:
# まとめて書くとこうなります

arr8 = arr3[(arr3 % 2) == 0]
print(arr8)

[0 2 4]


In [16]:
# 内積
# 記号 '@' を使って内積計算が可能です。

arr1 = np.array(list(range(2,12,2)))
arr3 = np.array(list(range(5)))
print(arr1)
print(arr3)

p = arr1 @ arr3
print(p)

[ 2  4  6  8 10]
[0 1 2 3 4]
80


### 二次元配列

numpyでは行列のような二次元配列も扱えます。  

#### 宣言

In [17]:
# 二次元配列の宣言
# この場合、引数はlistのlistとなります。

arr8 = np.array([[1,2,3,4,5], [6,7,8,9,10],[11,12,13,14,15]])

In [18]:
# 二次元配列をprint関数にかけるとこのような表示になります

print(arr8)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [19]:
# 要素数の取得

print(arr8.shape)

(3, 5)


#### 参照

In [20]:
# 要素の参照は「(第一次元引数),(第二次元引数)」の形式

print(arr8[1,2])

8


In [21]:
# それぞれの次元に対して範囲指定で参照することも可能

print(arr8[:2,2:])

[[ 3  4  5]
 [ 8  9 10]]


#### 計算

In [22]:
# スカラー積

a = np.array([[1,2,3],[4,5,6]])
b = a * 3
print(b)

[[ 3  6  9]
 [12 15 18]]


In [23]:
# スカラー和

a = np.array([[1,2,3],[4,5,6]])
c = a + 3
print(c)

[[4 5 6]
 [7 8 9]]


In [24]:
# 行列同士の和

d = a + b
print(d)

[[ 4  8 12]
 [16 20 24]]


In [25]:
# 行列と1次元配列の内積

a = np.array([[1,2,3],[4,5,6]])
x = np.array([3,2,1])
print(a)
print(x)

[[1 2 3]
 [4 5 6]]
[3 2 1]


In [26]:
# '@'による内積
# 行列とベクトルの積になる

y = a @ x
print(y)

[10 28]


In [27]:
# * による積
# ブロードキャスト機能により要素間の積になる

z = a * x
print(z)

[[ 3  4  3]
 [12 10  6]]


####  特別な配列の生成

In [28]:
# 要素数(2,3) すべての要素が0の配列

z23 = np.zeros((2,3))
print(z23)
print(z23.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


In [29]:
# 要素数(2,3) すべての要素が1の配列

o23 = np.ones((2,3))
print(o23)
print(o23.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


In [30]:
# 要素数(2,3) すべての要素が[0,1]間の一様乱数の配列

u23 = np.random.rand(2,3)
print(u23)
print(u23.shape)

[[0.8220017  0.73618103 0.24159392]
 [0.57484238 0.90228096 0.73743698]]
(2, 3)


In [31]:
# 要素数(2,3) すべての要素が平均0分散1の正規分布乱数の配列

s23 = np.random.randn(2,3)
print(s23)
print(s23.shape)

[[-0.33634642 -0.03324047 -0.95615384]
 [-0.4787232  -0.00488082  0.38166286]]
(2, 3)
