## Numpy入門2
7章の単回帰モデル実習での、学習データ準備の過程を詳しく説明しました。  
(この解説は書籍には含まれていません)

In [1]:
# 必要ライブラリimport
import numpy as np
from sklearn.datasets import load_boston

In [2]:
# 学習用データの読み込み
# Boston Dataセットというよく使われるデータなので、関数を呼び出すと自動的にダウンロードされます

boston = load_boston()
x_org, yt = boston.data, boston.target
feature_names = boston.feature_names

In [3]:
# 正解データ ytの表示(一部)

print(yt[:5])

[24.  21.6 34.7 33.4 36.2]


In [4]:
# x_orgの内容を調べる

print('クラス名:', type(x_org))
print('サイズ:', x_org.shape)
print('内容表示(一部):')
print( x_org[:5,:])
print('項目名: ', feature_names)

クラス名: <class 'numpy.ndarray'>
サイズ: (506, 13)
内容表示(一部):
[[6.3200e-03 1.8000e+01 2.3100e+00 0.0000e+00 5.3800e-01 6.5750e+00
  6.5200e+01 4.0900e+00 1.0000e+00 2.9600e+02 1.5300e+01 3.9690e+02
  4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 0.0000e+00 4.6900e-01 6.4210e+00
  7.8900e+01 4.9671e+00 2.0000e+00 2.4200e+02 1.7800e+01 3.9690e+02
  9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 0.0000e+00 4.6900e-01 7.1850e+00
  6.1100e+01 4.9671e+00 2.0000e+00 2.4200e+02 1.7800e+01 3.9283e+02
  4.0300e+00]
 [3.2370e-02 0.0000e+00 2.1800e+00 0.0000e+00 4.5800e-01 6.9980e+00
  4.5800e+01 6.0622e+00 3.0000e+00 2.2200e+02 1.8700e+01 3.9463e+02
  2.9400e+00]
 [6.9050e-02 0.0000e+00 2.1800e+00 0.0000e+00 4.5800e-01 7.1470e+00
  5.4200e+01 6.0622e+00 3.0000e+00 2.2200e+02 1.8700e+01 3.9690e+02
  5.3300e+00]]
項目名:  ['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


In [5]:
# x_org は506 x 13 の行列
# この行列から'RM' の列だけを抽出する

x_data = x_org[:,feature_names == 'RM']

In [6]:
# 結果確認

print('絞り込み後のサイズ', x_data.shape)
print('絞り込み後の内容(一部)')
print( x_data[:5])

絞り込み後のサイズ (506, 1)
絞り込み後の内容(一部)
[[6.575]
 [6.421]
 [7.185]
 [6.998]
 [7.147]]


In [7]:
# ダミー変数を追加

x = np.insert(x_data, 0, 1.0, axis=1)

In [8]:
# 結果確認

print('ダミー変数追加後のサイズ', x.shape)
print('ダミー変数追加後の内容(一部):')
print( x[:5,:])

ダミー変数追加後のサイズ (506, 2)
ダミー変数追加後の内容(一部):
[[1.    6.575]
 [1.    6.421]
 [1.    7.185]
 [1.    6.998]
 [1.    7.147]]


## 重回帰用データ追加

In [9]:
# 列(LSTAT: 低所得者率)の取得
x_add = x_org[:,feature_names == 'LSTAT']

In [10]:
# 結果確認
print('絞り込み後のサイズ', x_add.shape)
print('絞り込み後の内容(一部)')
print( x_add[:5])

絞り込み後のサイズ (506, 1)
絞り込み後の内容(一部)
[[4.98]
 [9.14]
 [4.03]
 [2.94]
 [5.33]]


In [11]:
# xに列を追加
x2 = np.hstack((x, x_add))

In [12]:
# 結果確認
print('絞り込み後のサイズ', x2.shape)
print('絞り込み後の内容(一部)')
print( x2[:5])

絞り込み後のサイズ (506, 3)
絞り込み後の内容(一部)
[[1.    6.575 4.98 ]
 [1.    6.421 9.14 ]
 [1.    7.185 4.03 ]
 [1.    6.998 2.94 ]
 [1.    7.147 5.33 ]]
